### ISSUE TITLE
IOError: [Errno2] No such file or directory: u'out/...'

### ISSUE THREAD

**Issue by fotakias** [mclmza/linkedin-learning-downloader#13] opened 2017-12-16 18:34 UTC
Thank you for the great script. Most of the times works like a charm.

There are cases i am facing the attached. Not really experienced with such tools but could it be something with the length of the path being too big? The windows folders are there and they may already have previous videos of the same chapter.

thank you in advance.

![image](https://user-images.githubusercontent.com/34606875/34073353-7eb41316-e2a0-11e7-8dce-abae55e88daf.png)

**Comment by mclmza** [comment] 2017-12-16 19:58
Can you share the course's url?

**Comment by fotakias** [comment] 2017-12-17 07:54
hi, thank you for your quick response:

Got this for all the following (and a few more, let me know if you need more) : 

https://www.linkedin.com/learning/nosql-for-sql-professionals
https://www.linkedin.com/learning/azure-development-essential-training-2-working-with-data
https://www.linkedin.com/learning/data-science-tips-weekly
https://www.linkedin.com/learning/database-foundations-administration

Thanks again for the great script... saved me hell lots of time!

**Comment by mclmza** [comment] 2017-12-18 10:06
Can you post more error screens related to the other courses?

**Comment by fotakias** [comment] 2017-12-18 13:06
yes, will post here as they come:
![2017-12-18 15-05-41](https://user-images.githubusercontent.com/34606875/34107484-12a36cf6-e405-11e7-9d6b-50ae4fc26142.png)

**Comment by fotakias** [comment] 2017-12-18 15:36
one more:
![2017-12-18 17-35-50](https://user-images.githubusercontent.com/34606875/34113951-09b7df40-e41a-11e7-91b8-180c98ca70ad.png)

**Comment by fotakias** [comment] 2017-12-19 07:01
different error here. URL: https://www.linkedin.com/learning/database-foundations-administration

![2017-12-19 08_58_37-anaconda prompt](https://user-images.githubusercontent.com/34606875/34144658-253058fc-e49b-11e7-95a1-13f5f7f65f45.png)

**Comment by mclmza** [comment] 2017-12-19 15:54
@fotakias the different error appears when you download too much videos, try to wait some time and run the script again. I'm still looking for the cause of the "No such file or directory" problem, but is a little bit difficoult for me because I don't have a premium account at the moment, so I can't replicate it.

**Comment by mclmza** [comment] 2017-12-19 15:59
@fotakias try to replace line 92:
`course_name = re.sub(r'[\\/*?:"<>|]', "", course_name)`
 with 
`course_name = re.sub(r'[\\/*?:.,"<>|]', "", course_name)`

and replace line 103:
`video_name = re.sub(r'[\\/*?:"<>|]', "", video['title'])`
with
`video_name = re.sub(r'[\\/*?:.,"<>|]', "", video['title'])`

Let me know,
Mike.

**Comment by milkshoes** [comment] 2017-12-19 16:32
I was just able to download the exact same course you are having trouble with just fine with the latest most recent regex pattern on Windows 10:

`
invalid_file_chars = r'[^A-Za-z0-9 ]+'
course_name = r.json()['elements'][0]['title']
course_name = re.sub(invalid_file_chars, " ", course_name)
`

![image](https://user-images.githubusercontent.com/2328121/34167566-1539c090-e4b0-11e7-8d0e-2e462f8d8988.png)

**Comment by milkshoes** [comment] 2017-12-19 16:47
I did however get an error in the course after:
https://www.linkedin.com/learning/implementing-a-data-warehouse-with-microsoft-sql-server-2012

![image](https://user-images.githubusercontent.com/2328121/34168327-43610274-e4b2-11e7-977e-a51414c51601.png)

**Comment by milkshoes** [comment] 2017-12-21 01:38
I've created a pull-request with your regex pattern update and it dos seem to work much better. I was able to run the script with no failures fro the courses listed above.

**Comment by mclmza** [comment] 2017-12-22 10:02
@milkshoes pull request merged.

**Closed** 2017-12-26 16:47 UTC
